Add USw to the inline search and proper installing
openstyles/stylus pull request #1223
Opened 2021-04-06 01:50 UTC by Gusted

@narcolepticinsomniac The search implementation like you said.
@vednoc Subscribe to the PR to follow it and if you like to insert your what USw is.

Well, guessing this one. 
Hi Tophf! Pretty code base you have here, you certainly can be proud about it.

So yeah, it's bad code. I know I know, no need to point that down.
Anyway it should add [USw](https://userstyles.world/) to the inline-search as a new option. Due to the having server-side searching and custom score/ranking. Basic functionality should work and I have a little hack to detect if a style has been downloaded from USw(reference note to `initialUrl`).

We currently don't have any analytics on the styles or reviews so that has been left out and later on when we have that, Il enable that part.

I hope some feedback on this PR and happy to refactor it and update the code. Or if you like for yourself edits are allowed for maintainers.

Regards,
Gusted

2021-04-06 03:25 UTC, tophf commented
The implementation in general will have to be much more complicated, probably, just like [it was previously](https://github.com/openstyles/stylus/commit/ad24ee0c15bb7ab8e7c24fff43946cc87676b4a8#diff-fc9d797a9416331e59e49b17615b597a432e29cc0923c34ae5d8aa026aa34bcd) until we switched to USO-archive: it will have to request a limited amount of results (using `page` and `pagesize` parameters) and cache the results in storage, which is necessary when the query matches hundreds or thousands of styles.

The current code in this PR has a lot of duplicated parts, which is bad because it increases maintenance burden: any change in the future will have to be duplicated which is both cumbersome and easy to overlook.

However the much bigger problem is that I see only ~30 styles on https://userstyles.world/explore so I don't think we will add it to Stylus yet. GreasyFork has accumulated 350 styles over more than a year and I still don't see it being useful enough to complicate our code, but we'll add it eventually if it keeps growing and more people use it to install styles.

2021-04-06 04:51 UTC, narcolepticinsomniac commented
> ...the much bigger problem is that I see only ~30 styles

Obviously, inline search integration for a measly couple dozen styles is silly based on the amount of content alone, but I think there's a catch 22 in that logic. We've seen a few other sites trying to provide a USO alternative, and none are having a whole lot of success aggregating content.

These new sites don't have the luxury of being the only userstyles host like USO. I don't think we can keep waiting for one of em to catch lightning in a bottle, and become useful. We need to go all in on one and try to make it succeed. Streamlining the submission process by integrating it, to make it as convenient as possible, would presumably raise awareness and speed up adoption - that's the PR I would've liked to have seen first.

I've been encouraging these guys because I think they're the best case scenario. They're motivated, and willing to implement pretty much anything we ask them to, within reason. They might've jumped the gun on inline search here, but I'm not even mad at that. Regardless of how useless their results are currently, I do think the ability for authors to see their styles included in search is a big factor in their willingness to bother publishing, so it's probably worthwhile for that alone.

Updating a single style on USO took like twenty minutes of pages failing to load last time I tried. That style's outdated now, and I can't even bring myself to update it again. I'm sure most authors feel the same, which means the archive ain't getting updated either.

We need an alternative that actually works, and it certainly seems like we're gonna need to help it succeed. These guys are willing to hook up all the features everyone wants, and we're familiar with them, so if we're gonna take a chance on one, this is it.

2021-04-06 06:43 UTC, tophf commented
> The implementation in general will have to be much more complicated, probably

A better alternative would be for the site to expose its index file which would be similar to USO-archive's one.
See also #1191.

2021-04-06 11:59 UTC, Gusted commented
> The current code in this PR has a lot of duplicated parts, which is bad because it increases maintenance burden: any change in the future will have to be duplicated which is both cumbersome and easy to overlook.

A lot can be merged together and have a simple check where necessary for `searchUserStylesWorld`, but mainly due to the difference we deliver of data and the format and how USO-Archives format their were too big to be done in a simple `if else` or even as a ternary condition but of course can be done so to reduce the amount of maintenance. I'm happy to do so.

> A better alternative would be for the site to expose its index file which would be similar to USO-archive's one.

That's definitely a option.
However, my point of view was bit that the indexing/searching was slow on startup. That's why the messy code to use our own search engine which is faster and allow specific queries. 

Seeing to add an API to send the index file similar to USO-archive excluding the key's names. Is an option and just for implementation sake, remove the search USW option and just add USw results into USO-archive results?

> See also #1191.

Will be noted and seems like some Hashing will be done server-side.

2021-04-06 12:35 UTC, tophf commented
It'll probably take decades for this index file to grow at least as big as the one on USO-archive so I'd say it's okay to use it directly in the same fashion, which should make the added code more or less trivial.

>just add USw results into USO-archive results?

Yeah.

2021-04-06 13:38 UTC, Gusted commented
https://github.com/openstyles/stylus/pull/1223/commits/b34bc513d4de5754eb870495e104cdc87f9e9057 relies on having the code on PR https://github.com/userstyles-world/userstyles.world/pull/36 running on the server.

2021-04-06 14:57 UTC, vednoc commented
> [b34bc51](https://github.com/openstyles/stylus/commit/b34bc513d4de5754eb870495e104cdc87f9e9057) relies on having the code on PR [userstyles-world/userstyles.world#36](https://github.com/userstyles-world/userstyles.world/pull/36) running on the server.

I just updated the server. 🎉

2021-04-07 03:04 UTC, tophf requested changes
Yay, it's much simpler now. There are some minor problems which I can fix myself after merging but you seemed willing to make the changes so I worked on a review instead.

2021-04-07 04:43 UTC, tophf commented on background/usercss-install-helper.js
> +      URLS.usw + 'api/style/*.user.css',
move it up to group with the existing `URLS` line

2021-04-07 06:53 UTC, Gusted commented on popup/search.js
> +      if (!results.length) {
Not sure, I remember some trouble I ran into and just removed that condition. Moving it back in.

2021-04-07 06:55 UTC, Gusted commented on popup/search.js
> +    results.length % PAGE_LENGTH ||
Good catch 😄

2021-04-07 06:57 UTC, Gusted commented on popup/search.js
> +   * @prop {bolean} uw - is USw style
It was later used to render things differently than uso(screenshots etc) but yeah It can actually be simplified trough the extract function.

2021-04-07 07:20 UTC, Gusted commented
Hey @tophf!

Great catches on the requested changes. However due now we have 2 broken code. 1 need to be done on our side for the server and the other one is a puzzle to figure out(see comments in new commit).

Regards,
Gusted

2021-04-07 07:28 UTC, tophf commented on popup/search.js
> +    // Any recommendation how to detect USw here?
You can add `isUsw` to each entry when downloading the index in fetchIndex()

2021-04-07 15:20 UTC, tophf approved these changes

2021-04-08 02:08 UTC, vednoc commented
I updated the API and pushed the new release to the server. It's now ready for testing.

2021-04-08 02:49 UTC, tophf commented on popup/search.js
> +      if (!results.length) {
You've restored it in the wrong place :-), should have been on line 201. I've fixed it now.

2021-04-09 07:21 UTC, Gusted commented
Good to go from my side, everything seems to be working as my intentions.

2021-04-18 00:27 UTC, vednoc commented
Added weekly and total installs as well as last updated date to our API. Is there anything else that needs to be added?

2021-04-18 03:45 UTC, tophf commented
I'm waiting for @narcolepticinsomniac to give it a spin just in case. Code is fine by me.

2021-04-18 11:59 UTC, narcolepticinsomniac commented
Alright, I'm mostly testing vednoc's USw tweaks style on USw. External link on top of image is broken, and leads to the archive. Not sure if this is expected behavior, but you can't click again to uninstall, since a config button comes up instead. If this is our doing, it kinda sucks.

There's no updated dates, or ratings, but apparently both are a work in progress. Ratings will take time even once the feature's ready, but updated dates need to be there. 

One of the main objectives with anything USw related should be to raise awareness. I suggest we add a checkbox for listing USw styles first, enabled by default. Some sorta visual indication on the entry itself might be useful. Perhaps a little 'USw' link somewhere. WDYT @tophf ?

2021-04-18 12:44 UTC, tophf commented
Fixed the bugs and added the USW icon to the title. As for a checkbox, I couldn't see its usefulness to an average Joe.

2021-04-18 12:52 UTC, narcolepticinsomniac commented
> As for a checkbox, I couldn't see its usefulness to an average Joe.

Checkbox, or not, I think we should prioritize USw results. There ain't a whole lot, and their stats are nonexistent, so they'll be getting buried for the foreseeable future. Not to mention, early adopters will be mostly enthusiastic authors, and styles will be up-to-date, so they should be pretty good.

2021-04-18 13:06 UTC, tophf commented
The styles aren't curated there so we can't just assume it'll always be better. I'd rather we take a conservative approach and only show USW results right before a USO style with an identical name.

2021-04-18 13:23 UTC, narcolepticinsomniac commented
> I'd rather we take a conservative approach

That's why I suggested making it optional. I'd prefer to push it as hard as possible, while providing an opt-out for the heavy-handedness. I'm focusing on every little advantage we can provide to make this work, which factors into suggesting things I might not normally. I feel like this is a cuttable corner, but if I'm not convincing, we could just go with your approach.

2021-04-18 13:34 UTC, Gusted commented
> There's no updated dates, or ratings, but apparently both are a work in progress. Ratings will take time even once the feature's ready, but updated dates need to be there.

Ratings are indeed work in progress. And the updated date got a little bit lost, https://github.com/userstyles-world/userstyles.world/commit/47809a62d67ca3e8b41e1a09ae848e6ed254d914 + it will send lower cased categories and will then show up the 2 USw styles.

2021-04-18 13:40 UTC, tophf commented
I'm not convinced users will benefit from USW styles being stuffed down their throats. Here's another solution I'm comfortable with: switch to `Updated` sort order by default and make it remember the user's choice so USW styles should be prevalent there.

2021-04-18 14:07 UTC, tophf commented
Added the code. It will work when Gusted's fix for USW index is applied to the live server.

2021-04-18 15:20 UTC, vednoc commented
I updated the server about half an hour ago, just been busy fixing small issues with API. The inclusion of our mascot next to style name brings a smile to my face. 😊

2021-04-18 15:35 UTC, tophf commented
@narcolepticinsomniac, I guess we can add a short USW promo in our README and/or wiki? And maybe a full-width promo link at the bottom of the header panel in the manager e.g. `Upload and discover styles on userstyles.world` with an icon?

2021-04-20 17:40 UTC, merged